### ISSUE TITLE
String Syntax Issue

### ISSUE THREAD

**Issue by born2defy** [purescript-contrib/atom-language-purescript#15]
Not sure if this is an issue with Atom or with the plugin, but I am noticing that whenever a string of over 96 characters is included on a line, anything that follows the string on the same line is also highlighted as if it were a string, even if it is a totally different type.

**Comment by nwolverson** [comment]
Seems like this may be Atom design choice https://github.com/atom/atom/issues/1667 - I see this with other things than strings, though didn't see the number 96 in my test case.

**Comment by born2defy** [comment]
Ah, you are correct.  

Adam

**Comment by nwolverson** [comment]
Closing this per the linked atom issue - track that issue for updates.
