### ISSUE TITLE
Issues with icons when using Atom Material

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [purescript-contrib/atom-language-purescript#16]
So I've been seeing this for a while but only now decided to report it.
When I'm using Atom Material theme (which is always) Purs icons get reized and distorded. I suppose that the first picture is how everything looks without the theme and the second one is with the theme.

Is this an issue with Atom Material or Atom Lang Purs?

normal:
http://i.imgur.com/SbBNkNY.png
material:
http://i.imgur.com/dEJ2v8v.png

**Comment by nwolverson** [comment]
Actually there is no icon in this package.

I did sneak a PS icon into [atom-ide-purescript](https://github.com/nwolverson/atom-ide-purescript). Probably there's an issue with the CSS of that (i.e. my) package, I think it works with file-icons package somehow

**Comment by nwolverson** [comment]
Migrated to https://github.com/nwolverson/atom-ide-purescript/issues/110
