### ISSUE TITLE
Highlight "foreign import data" correctly

### ISSUE THREAD

**Issue by ianbollinger** [purescript-contrib/atom-language-purescript#23]
Currently `format import data` declarations are not highlighted correctly.

````purescript
foreign import data Example = # ! -> *
````

**Comment by nwolverson** [comment]
But isn't the syntax

```purescript
foreign import data Example :: # ! -> *

```

**Comment by ianbollinger** [comment]
Whoops, typo. :D  Still doesn't work, though.

**Comment by nwolverson** [comment]
As the highlighting in Atom is not per github, it "looks ok" to me - but yes the `data` should be in the same keyword class as foreign,import.
