### ISSUE TITLE
Built-in types aren't autocompleted

### ISSUE THREAD

**Issue by ianbollinger** [purescript-contrib/atom-language-purescript#28]
It would be good if autocompletion worked for built-in types such as Boolean, Number, etc.

**Comment by nwolverson** [comment]
Hmm. This package provides no autocomplete, I'm not sure it should start - probably more suited to include in https://github.com/nwolverson/atom-ide-purescript - I think there was even consideration of just returning `Prim` types from psc-ide.

**Comment by ianbollinger** [comment]
Okay, we can probably close this then. I noticed a few plug-ins *do* add add completions in their settings file, like language-java.

**Comment by nwolverson** [comment]
Certainly leave it open for comment. We should certainly ensure that at least one of those options will provide it, but there's maybe a place to do both

**Comment by nwolverson** [comment]
https://github.com/purescript/purescript/issues/2925

**Comment by nwolverson** [comment]
Primitive types are now completed via ide-purescript https://github.com/nwolverson/atom-ide-purescript/issues/152 so I don't think there's a need to do so here.
