### ISSUE TITLE
String length > 94 chars leads to incorrect highlighting for the follow-on text

### ISSUE THREAD

**Issue by Andrew-Webb** [purescript-contrib/atom-language-purescript#37]
Exhibit A...

![94_char_string](https://cloud.githubusercontent.com/assets/3470891/23172963/86b35b62-f84f-11e6-8518-6aff5d72fde3.png)

Here we see correct highlighting.

But now we add one extra character to the string...

![95_char_string](https://cloud.githubusercontent.com/assets/3470891/23172984/9d423c22-f84f-11e6-91b8-22d203be7f49.png)

It's definitely related to string length and not line length.  In the case depicted by the second screenshot, I can reduce `uri1` to `u1` and it doesn't affect the outcome.

I can go on adding chars to the string, and the syntax highlighting remains wrong.

Of course the example string is hypothetical, but I have genuine URIs that are way longer.

I'm using `Atom.io 1.14.3 ia32` on Windows 7.  `language-purescript` package = 0.8.2

**Comment by nwolverson** [comment]
This is an unfortunate atom restriction atom/atom#1667 , see also #18 

You should be able to get around this by splitting strings across lines or possibly adding a close quote in a comment :/
