### ISSUE TITLE
Data type records with nested record types break highlighting

### ISSUE THREAD

**Issue by MiracleBlue** [purescript-contrib/atom-language-purescript#39]
It seems whenever I have a record data type with a nested record, the nested record breaks the rest of the highlighting for the record data type.  This only happens on data types it seems, as types work just fine.

A screenshot is attached of what happens in my editor in this case.

Atom version: 1.16.0-beta0
OS: macOS Sierra 10.12.3
language-purescript: 0.8.2

![image](https://cloud.githubusercontent.com/assets/23368/24584695/056086d2-17b9-11e7-9fc1-fdb6d958ff71.png)

**Comment by MiracleBlue** [comment]
This is still an issue, although I've hardly noticed it much since I don't really use this much nesting in my types.  Not sure if it's *really* worth fixing, but I'll leave this here anyway.

Atom version: 1.21.0-beta1
OS: macOS Sierra 10.12.6
language-purescript: 0.8.2

**Comment by nwolverson** [comment]
I had a crack at this a while back but it's pretty screwy, I think the bit that looks OK just now is for the wrong reasons

**Comment by MiracleBlue** [comment]
Yeah I imagined as much.  Happy to leave this on the backburner as I don't really run into it much at all anyway, and no one else seems to be complaining :)

Cheers!

**Comment by MiracleBlue** [comment]
Hmm, actually, I think I see what you mean now from your comment "the bit that looks OK just now is for the wrong reasons".  I have a very heavily customised stylesheet, and like to make certain symbols bold (like :: for example).  When I define a record type in a data type, like you see above, I am able to style the double-colon symbol, since it's recognised and wrapped.  In the type alias record, like above, it's not.  Along with a bunch of other styling differences, such as the curly braces and the attribute names.

Within the typed alias record, the cursor scope comes out as the following:
```
source.purescript
meta.declaration.type.type.purescript
meta.type-signature.purescript
```

Whereas the data type record gives
```
source.purescript
meta.declaration.type.data.purescript
meta.declaratyion.type.data.record.block.purescript
meta.record-field.type-declaration.purescript
meta.type-signature.purescript
```

It definitely appears the parser isn't recognising the type alias record as a record at all, and is just falling back to some defaults, like variable types etc.  If I wanted to have a go at investigating, where do you suggest I start looking?  And any other advice etc you could give?  Cheers!

**Comment by nwolverson** [comment]
Worth looking at this PR/comments https://github.com/purescript-contrib/atom-language-purescript/pull/38
